version: '3.9'

services:
  database:
    container_name: database-server
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    networks:
      - backnet
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - backnet
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: unless-stopped
    env_file:
      - project.env
    networks:
      - backnet
    depends_on:
      - database

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backnet
    expose:
      - 6379

  todo-api:
    build:
      context: todo-api
      dockerfile: Dockerfile.prod
    image: todo-api-prod
    restart: 'on-failure'
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    networks:
      - backnet
      - frontnet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
    ports:
      - 7800:7800
    networks:
      - backnet
      - frontnet

  todo-ui:
    build:
      context: todo-ui
      dockerfile: Dockerfile.prod
    image: todo-ui-prod
    restart: 'on-failure'
    ports:
      - 3000:80
    depends_on:
      - todo-api
    networks:
      - backnet
      - frontnet
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

volumes:
  astro_node_modules:

networks:
  backnet:
  frontnet:
